<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * BomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BomRepository extends \Doctrine\ORM\EntityRepository
{
    public function getBomsPerPage($page, $nbPerPage)
    {
        $query = $this->createQueryBuilder('bom')
            ->orderBy('bom.created', 'DESC')
            ->setFirstResult(($page - 1) * $nbPerPage)
            ->setMaxResults($nbPerPage);

        return new Paginator($query, true);
    }

    public function getBomLinesAlternatives($id)
    {
        return $this->createQueryBuilder('bom')
            ->leftJoin('bom.lines', 'line')
            ->addSelect('line')
            ->leftJoin('line.alternatives', 'alternative')
            ->addSelect('alternative')
            ->where('bom.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getSingleResult()
            ;
    }
}
