<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * SupplierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSuppliersPerPage($page, $nbPerPage)
    {
        $query = $this->createQueryBuilder('supplier')
            ->orderBy('supplier.name', 'ASC')
            ->setFirstResult(($page - 1) * $nbPerPage)
            ->setMaxResults($nbPerPage);

        return new Paginator($query, true);
    }

    public function getSuppliersWithAPI()
    {
        $query = $this->createQueryBuilder('supplier');
        $query->where($query->expr()->isNotNull('supplier.interface'));
        $query->andWhere('supplier.enabled = :true');
        $query->setParameter('true', true);
        return $query->getQuery()->getResult();
    }
}
