homeredirect:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: home
        permanent: true

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale: en|fr

api_digikey:
    resource: "@APIDigikeyBundle/Controller/"
    type:     annotation
    prefix:   /api/digikey

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /{_locale}
    requirements:
        _locale: en|fr

api_excel:
    resource: "@APIExcelBundle/Controller/"
    type:     annotation
    prefix:   /api/excel
