homeredirect:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: homepage
        permanent: true

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/admin/app
    requirements:
        _locale: en|fr

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /{_locale}
    requirements:
        _locale: en|fr
