services:
    before_request_listener:
        class: AppBundle\EventListener\BeforeRequestListener
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage"]
        tags:
            -
                name: kernel.event_listener
                event: kernel.request
                method: onKernelRequest